name: "publish-pypi"

on:
  release:
    types: [created]
  push:
    branches:
      - main
    paths:
      - "app/**"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        working-directory: ./app
        run: uv sync

      - name: Build package
        working-directory: ./app
        run: uv build

      - name: Publish package
        working-directory: ./app
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
