name: "publish-pypi"

on:
  release:
    types: [created]
  push:
    branches:
      - main
    paths:
      # Trigger on changes to Pipfile.lock or the package itself.
      - "Pipfile.lock"
      - "app/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          # This action has built-in caching for pipenv. It automatically uses
          # Pipfile.lock as the cache key.
          cache: "pipenv"

      - name: Install build tools
        run: pip install pipenv build twine

      - name: Install dependencies from Pipfile.lock
        run: pipenv sync --dev

      - name: See file structure 1
        run: ls -R

      - name: Build package
        # Set the working directory to './app' before running the build.
        working-directory: ./app
        # This will create the 'dist' directory inside 'app' -> './app/dist/'.
        run: python -m build

      - name: See file structure 2
        run: ls -R

      - name: Publish package to PyPI
        run: python -m twine upload --non-interactive app/dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
